### ISSUE TITLE
Сделать, чтобы враги, попадающие в киллзону исчезали без звука

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#1]

**Comment by xttx** [comment]
Можно делать двумя способами:
- можно добавлять несколько дочерних объектов со скриптом Gun
- можно в настройках указать сколько спавнить пулек (параметр bullet_grid, указывается количество по x и по y) и выставлять bullet_grid_offset_H и bullet_grid_offset_V (расстояние между пульками по x и по y).
