### ISSUE TITLE
Добавить VFX при смерти противника или игрока

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#10]
На текущий момент предполагаю спавн на месте кораблика объекта, который может быть либо мешью с анимацией, либо VFX графом, да и вообще пофиг чего. Поидее, будет достаточно просто дать возможность спавнить список объектов на месте смерти. То, что заспавнится должно сохранять иннерцию, то есть, если самолётик летел вперёд, то и все эффекты полетят туда же, пока не исчезнут.

**Comment by xttx** [comment]
Done.
Что бы заспавненный объект продолжал двигаться в сторону последнего перемещения кораблика, на нём должен висеть скрипт Linear_Movement. Параметры не важны.
