### ISSUE TITLE
У лазера добавить лимиты экрана, чтобы не вылазил за пределы обзора если стреляешь в верхней точке

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#11]

**Comment by xttx** [comment]
Тут есть ньюанс: если подстраивать именно размер объекта лазера, то он будет перескейливаться на ходу, когда игрок будет двигаться вверх/вниз с включённым лазером. Ты именно этого хочешь, или всё-таки скейлинг объекта не трогать, а просто игнорить коллизию лазера, если она произошла слишком далеко от камеры, за экраном?

**Comment by Astralis1991** [comment]
Наверное, пускай игнорит коллизию и дамаг, если попадание за экраном, чтобы не было странных анимаций. Этого должно вроде хватить на любую ситуацию...

**Comment by xttx** [comment]
Done.
