### ISSUE TITLE
VFX при попадании пульки

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#13]
Я пока не очень понимаю чисто технически, как это сделать. Задача состоит в том, чтобы при попадании пульки от корпуса, в месте её попадания, отлетали искры или что-то типа того, короче, спавнился VFX. Может быть, возможно узнавать место, где произошла коллизия, чтобы там прямо и спавнить? В общем, хорошо бы что-нибудь придумать =)

**Comment by xttx** [comment]
Место - можно. А вот направление - крайне сложно. Просто спавнить в месте попадания устроит?

**Comment by Astralis1991** [comment]
На данный момент спавнить в точке попадания, думаю, более чем достаточно будет.

**Comment by xttx** [comment]
Done.
