### ISSUE TITLE
Реализация не только попадания игроком на разной высоте, но и стрельбу врагов.

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#14]
Пока ещё не тестил коллайдеры на попадание, но пока ковырялся с туррелькой пришла мысль, а как вообще она будет стрелять? Если она находится ниже игрока, то стрелять она должна тоже как-то хитро. Чтобы её пульки спавнились на нулевой высоте. Пока хз, что с этим делать, просто как пища для размышлений.

**Comment by xttx** [comment]
Можно и так, но тогда нужно проецировать её координату в 2D каждый кадр (что бы проверять коллизию).
Но я бы просто спавнил её сразу на нулевой высоте. Тогда проецировать 3д в 2д пришлось бы только один раз, при старте этой пули.

**Comment by Astralis1991** [comment]
Да, отлично! просто нужно совместить изначальную позицию пули туррели, чтобы была видимость, будто вылетает из дула. А дальше, да, я тоже так и думал, пускай летит, как обычная.

**Comment by xttx** [comment]
Done. In GUN object set "project_Y_0" to true.
