### ISSUE TITLE
Насчёт энвайронмента...

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#2]
К той теме со спавнером фоновых объектов. Было бы круто сделать возможность отдельно от всего контролировать скорость движения этого самого энвайронмента.  То есть, примерно по схеме: заспавнить и пустить вперёд с определённой скоростью. Отдельно от вражеских самолётов или движения самого игрока.

**Comment by xttx** [comment]
See https://github.com/xttx/ShmupScripts/issues/3#issuecomment-1152220577
