### ISSUE TITLE
Если не слишком геморно, можно сделать, чтобы вражеские кораблики лопались за лимитами без VFX и без звука? А то сами улетели, а взрывы видно =)

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#21]

**Comment by xttx** [comment]
VFX убрал, а звук-то откуда? Если ты про звук, который SFX_Death, то этого звука не должно было быть, если кораблик погибал за лимитами. Если у тебя звук был - значит что-то где-то не так, надо у тебя смотреть. Перепроверь.

**Comment by Astralis1991** [comment]
Перепроверил, всё отлично, видимо, я что-то перепутал.
