### ISSUE TITLE
Есть проблема с SFX вражеских корабликов. 

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#22]
Когда кораблик подлетает близко к нижнему лимиту камеры, он продолжает стрелять. Но, происходит ситуация, что кораблик выстрелил, а пулька почти в ту же секунду уничтожилась, но при этом успела начать воспроизводить звук при стрельбе. В итоге слышно этот звук не до конца, а несколько фреймов, получается очень рвано и резко обрубается.

**Comment by xttx** [comment]
Враги тепеь перед уничтожением ждут, пока доиграются их звуки. Это может вызвать задержку при их убивании, или же они вообще могут не уничтожится если звук играет постоянно (например, если они непрерывно стреляют лазером?).

**Comment by Astralis1991** [comment]
Стреляния лазером будут, но не непрерывно. Наверное, пока париться не о чем, пускай будет так.
