### ISSUE TITLE
Отдельные лимиты для энвайронмента всё таки нужны...?

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#23]
Когда длинный клонированый паровоз доезжает до низа, видно, как оно исчезает (в случае, когда объект летит на заднем плане, то есть, находится много ниже корабликов и игрока). За счёт перспективы получается, что видно, как энвайронмент наезжает на уничтожатор и просто испаряется =)

**Comment by xttx** [comment]
Done.
