### ISSUE TITLE
--ИИ-- Сделать скрипт таргетер, который вешался бы на самолётик

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#24]
Пока кораблик летит по независимой траектории, нужно чтобы он таргетился на игрока ВСЁ время полёта. Полёт может быть как по прямой, так и по сплайну, либо с анимацией. Грубо говоря, можно сделать его аддитивным? Скорость поворота за движущимся игроком должна регулироваться, то есть, таргетинг должен производиться за определённое время (мб градусы в секунду...). А дальше, пока оно таргетится, происходит всё то же самое, что обычно.
Возможно ли чисто физически, чтобы самолётик при повороте за игроком немного накренялся, на манер самолёта игрока? То есть, во время поворачивания поворачивался чутка.

**Comment by xttx** [comment]
Done.
