### ISSUE TITLE
Не забыть реализовать активацию стрельбы/щита/лазера на разные кнопки =) Щит должен уметь работать как вкл/выкл 

### ISSUE THREAD

**Issue by Astralis1991** [xttx/ShmupScripts#8]

**Comment by xttx** [comment]
Щит и так уже работает как вкл/выкл.

**Comment by xttx** [comment]
В объекте GUN теперь есть параметр Fire_Index. Его надо ставить от 0 до 3 включительно. Соответственно в Global_Settings теперь прописываются 4 кнопки управления Fire1...Fire4. Какой Fire_Index у гана поставить - на ту кнопку он и будет стрелять.
